<?
$PERM["admin"]["2"]="D";
$PERM["admin"]["3"]="D";
$PERM["admin"]["4"]="D";
$PERM["admin"]["5"]="D";
$PERM["admin"]["6"]="D";
$PERM["admin"]["*"]="D";
$PERM["search"]["6"]="W";
$PERM["products"]["6"]="W";
$PERM["services"]["6"]="W";
$PERM["news"]["6"]="W";
$PERM["contacts"]["6"]="W";
$PERM["company"]["6"]="W";
$PERM["index.php"]["6"]="W";
$PERM["/"]["*"]="R";
?>